### PR TITLE
Converted .png to .jpg images (issue #3)

### PR DESCRIPTION
**Pull request by carstorm**
Solves Issue #3

### CODE REVIEW

**Comment by darkhax** [comment]
Not exactly. Check [this](https://github.com/MinecraftModDevelopment/MinecraftModDevelopment.github.io/search?utf8=%E2%9C%93&q=.png)

**Comment by TheCodedOne** [comment]
This is half a PR, please change the required fields in the html.

**Comment by carstorm** [comment]
Woops, Though I was forgetting something :). will do.

**Comment by carstorm** [comment]
I fixed the issue and hope that I updated the PR correctly.

**Comment by darkhax** [comment]
Looks good to me @TheCodedOne

**Comment by TheCodedOne** [comment]
Yep, seems fine to me.

**Comment by darkhax** [comment]
If it's fine, why not merge it? x)

**Comment by TheCodedOne** [comment]
i did press the merge button, github decided it didn't want to do anything

**Pull request merged**
